local parser = require("nvim-obsidian.template.parser")

describe("template parser", function()
    it("parses text and placeholders", function()
        local tokens = parser.parse("# {{title}} on {{date}}")
        assert.are.equal(4, #tokens)
        assert.are.equal("text", tokens[1].type)
        assert.are.equal("placeholder", tokens[2].type)
        assert.are.equal("title", tokens[2].name)
        assert.are.equal("placeholder", tokens[4].type)
        assert.are.equal("date", tokens[4].name)
    end)

    it("keeps invalid placeholders as text", function()
        local tokens = parser.parse("{{title|upper}}")
        assert.are.equal(1, #tokens)
        assert.are.equal("text", tokens[1].type)
        assert.are.equal("{{title|upper}}", tokens[1].value)
    end)
end)
