---@diagnostic disable: undefined-global

local assertions = require("tests.helpers.contract_assertions")

describe("domain contracts", function()
    it("vault catalog contract exposes stable operations", function()
        local contract = require("nvim_obsidian.core.domains.vault_catalog.contract")
        assertions.assert_contract_shape(contract, "vault_catalog")
        assertions.assert_api_operation(contract, "upsert_note")
        assertions.assert_api_operation(contract, "remove_note")
        assertions.assert_api_operation(contract, "find_by_title_or_alias")
    end)

    it("journal contract exposes stable operations", function()
        local contract = require("nvim_obsidian.core.domains.journal.contract")
        assertions.assert_contract_shape(contract, "journal")
        assertions.assert_api_operation(contract, "classify_input")
        assertions.assert_api_operation(contract, "build_title")
        assertions.assert_api_operation(contract, "compute_adjacent")
    end)

    it("wiki link contract exposes stable operations", function()
        local contract = require("nvim_obsidian.core.domains.wiki_link.contract")
        assertions.assert_contract_shape(contract, "wiki_link")
        assertions.assert_api_operation(contract, "parse_at_cursor")
        assertions.assert_api_operation(contract, "resolve_target")
    end)

    it("template contract exposes stable operations", function()
        local contract = require("nvim_obsidian.core.domains.template.contract")
        assertions.assert_contract_shape(contract, "template")
        assertions.assert_api_operation(contract, "register_placeholders")
        assertions.assert_api_operation(contract, "render")
    end)

    it("dataview contract exposes stable operations", function()
        local contract = require("nvim_obsidian.core.domains.dataview.contract")
        assertions.assert_contract_shape(contract, "dataview")
        assertions.assert_api_operation(contract, "parse_blocks")
        assertions.assert_api_operation(contract, "execute_query")
    end)

    it("search ranking contract exposes stable operations", function()
        local contract = require("nvim_obsidian.core.domains.search_ranking.contract")
        assertions.assert_contract_shape(contract, "search_ranking")
        assertions.assert_api_operation(contract, "score_candidates")
        assertions.assert_api_operation(contract, "select_display")
    end)
end)
